### ISSUE TITLE
getting an error when i try to build (no edits, simply attempting to build the project as is)

### ISSUE THREAD

**Issue by AndrewRober** [sighthoundinc/SighthoundVideo#3]
```
1/3] Building C object CMakeFiles/optsearches.dir/optsearches.c.obj
[2/3] Linking C shared library optsearches.dll
[2/3] Install the project...
Building triggers from /c/Users/andre/Documents/GitHub/SighthoundVideo/backEnd/triggers into /tmp/install - done
~/Documents/GitHub/SighthoundVideo
Building final SV project
>>>>> PATH=/tmp/tools/svpython/:/c/Users/andre/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/........
>>>>> PYTHON=/tmp/tools/svpython/python
/c/msys64/usr/share/bash-completion/completions/make: line 93: syntax error near unexpected token `('
/c/msys64/usr/share/bash-completion/completions/make: line 93: `            --assume-new | -!(-*)[foW])'
```

**Comment by w3sip** [comment]
You seem to be building in msys shell. This is not something we tested. Please follow the exact steps, with the same environment as outlined in README (Visual Studio tools shell, with git binary tools etc).

**Comment by AndrewRober** [comment]
> You seem to be building in msys shell. This is not something we tested. Please follow the exact steps, with the same environment as outlined in README (Visual Studio tools shell, with git binary tools etc).

I'm using Git Bash, MSVC shell opens the git bash by default, am i getting this wrong? did you mean bash as in WSL?

![image](https://user-images.githubusercontent.com/54873972/231853040-fe2bb594-2f31-4176-a6ab-dc0ca3bf7858.png)

**Comment by w3sip** [comment]
You seem to be opening WSL shell, no? What I mean is this:

<img width="1466" alt="Screen Shot 2023-04-13 at 2 53 06 PM" src="https://user-images.githubusercontent.com/4392548/231856015-ea997527-1404-47a7-836e-bd36176e35f8.png">


I've just done a fresh clone, and things seem to be building fine. The output start to end, including the script for environment setup is the screenshot. The only "quirky" thing in this environment is that `make.exe` in `u:\git\mingw64\bin` had been replaced with the one from `msys2`:
- download msys2 installer
- install and run msys2
- pacman -Su make
- cp /usr/bin/make.exe /u/git/mingw64/bin/ (alter destination to where your git is)

I've just tested it with a make pulled out of fresh msys2 install, as well as the prior version of make I had both work:
```
u:\code\SighthoundVideo>u:\git\mingw64\bin\make.exe.works.exe -version
GNU Make 4.3
Built for x86_64-pc-msys
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

u:\code\SighthoundVideo>u:\git\mingw64\bin\make.exe -version
GNU Make 4.4.1
Built for x86_64-pc-msys
Copyright (C) 1988-2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

The version that ships with git bash does not work:

```
u:\code\SighthoundVideo>u:\git\mingw64\bin\make.exe.bak.exe -version
GNU Make 4.3
Built for Windows32
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by AndrewRober** [comment]
@w3sip w3sip Thank you very much for your help; very much appreciated, it turned out that even the make from msys2 didn't work for me, had to get one using chocolate, also had to add the scripts folder in the environment variables but that was obvious, oh and the inno might be hard coded to check for version 5
