### ISSUE TITLE
Unable to setup sighthound on windows system

### ISSUE THREAD

**Issue by himanshunethues** [sighthoundinc/SighthoundVideo#6]
Hi There,

Just wanted to inform you I am setting up the sighthound on my windows system and facing the error with the Ninja program.

Please review the attached screenshot showing the error.

Can you please share a proper developer documentation that list out all the steps required to be perform along with the prerequisite having correctly mentioned versions of the dependencies to be installed or if you can give me an idea what I am doing wrong in the setup then it would be really helpful.

Looking forward to hear from you.

Kind Regards,
Himanshu Rehani
![image(2)](https://github.com/sighthoundinc/SighthoundVideo/assets/74190703/63415276-74a9-4c92-a932-04ee16ef4631)

**Comment by mufaawan** [comment]
@himanshunethues  can you show me the start of the log just after execution of the `bash ./build.sh` command. May be it's becuase of the incomplete pull of Windows library inside /root/win folder.

**Comment by w3sip** [comment]
@himanshunethues - you're running in mingw shell. This isn't supported. Please use MSVC build shell.

**Comment by himanshunethues** [comment]
Hi @mufaawan 

Please review the start of execution in the attached screenshot.

Is it possible to have a call over skype or zoom and get this setup completed. Please confirm.

Thanks.
![Screenshot (1)](https://github.com/sighthoundinc/SighthoundVideo/assets/74190703/3fafa14f-3944-4cff-82b3-c61ff9461012)

**Comment by w3sip** [comment]
Again, you're using mingw/msys shell. Please follow the instructions in README.

**Comment by mufaawan** [comment]
> Hi @mufaawan
> 
> Please review the start of execution in the attached screenshot.
> 
> Is it possible to have a call over skype or zoom and get this setup completed. Please confirm.
> 
> Thanks. ![Screenshot (1)](https://user-images.githubusercontent.com/74190703/259134703-3fafa14f-3944-4cff-82b3-c61ff9461012.png)

Hello @himanshunethues , yes I can help you definitely. You can drop me an email. Mufaawan@gmail.com.
