### ISSUE TITLE
Provide documentation about building the project from sources on MacOS and common Linux-based OS.

### ISSUE THREAD

**Issue by l3acucm** [sighthoundinc/SighthoundVideo#7]
The README.md has no helpful info about steps that must be reproduced to build the project from MacOS and Linux. It is mandatory for further workflow including dockerization and CI/CD configuration.

**Comment by w3sip** [comment]
MacOS is no different from Windows - check out the source, have the requirements specified in README available, run `buildSV.sh`. 
Linux is not a supported OS for Sighthound Video (and never was).
